In [1]:
import numpy as np

a = np.array([[0, 1, 2, 3],
              [1, 2, 3, 4],
              [2, 3, 4, 5]])

print(a)


[[0 1 2 3]
 [1 2 3 4]
 [2 3 4 5]]


In [2]:
# 行列積

a = np.array([[0, 1, 2],
              [1, 2, 3]])

b = np.array([[2, 1],
              [2, 1],
              [2, 1]])

print(np.dot(a, b))

[[ 6  3]
 [12  6]]


In [4]:
#  入力と重みの積の総和

x = np.array([0, 0.5, 1.0])
w = np.array([[-1, 1],
              [1, -1],
              [-1, 1]])

print(np.dot(x, w))

[-0.5  0.5]


In [5]:
# 転置

a = np.array([[1, 2, 3],
              [4, 5, 6]])

print(a.T)

[[1 4]
 [2 5]
 [3 6]]


In [6]:
# 転置によって行列積が可能になる

a = np.array([[0, 1, 2],
              [1, 2, 3]])

b = np.array([[0, 1, 2],
              [1, 2, 3]])

print(np.dot(a, b.T))

[[ 5  8]
 [ 8 14]]
