In [12]:
import torch
import torch.nn as nn
import torch.nn.functional as F

# 乱数のシードを固定
torch.manual_seed(0)

# 3ノード → 2ノードの全結合層
fc = nn.Linear(3, 2)

print(fc.weight)
print(fc.bias)

# 入力値
x = torch.tensor([1.0, 2.0, 3.0])

# 線形変換
u = fc(x)
print(u)

# 非線形変換（ReLU関数）
# ReLU(x) = max(0, x)
h = F.relu(u)
print(h)

# 目的関数
## 目標値
t = torch.tensor([1.0, 3.0])
## 予測値
y = torch.tensor([2.0, 4.0])
## 平均二乗誤差
loss = F.mse_loss(t, y)
print(loss)

Parameter containing:
tensor([[-0.0043,  0.3097, -0.4752],
        [-0.4249, -0.2224,  0.1548]], requires_grad=True)
Parameter containing:
tensor([-0.0114,  0.4578], requires_grad=True)
tensor([-0.8219,  0.0526], grad_fn=<ViewBackward0>)
tensor([0.0000, 0.0526], grad_fn=<ReluBackward0>)
tensor(1.)
